Console.WriteLine("  ___  ___  ___");
Console.WriteLine("  | |__| |__| |");
Console.WriteLine("  |           |");
Console.WriteLine("   \\_________/");
Console.WriteLine("    \\_______/");
Console.WriteLine("     |     |");
Console.WriteLine("     |     |");
Console.WriteLine("     |     |");
Console.WriteLine("     |     |");
Console.WriteLine("     |_____|");
Console.WriteLine("  __/       \\__");
Console.WriteLine(" /             \\");
Console.WriteLine("/_______________\\");