Console.WriteLine(@"     /~\");
Console.WriteLine(@"    ( oo|");
Console.WriteLine(@"    _\=/_");
Console.WriteLine(@"   /  _  \");
Console.WriteLine(@"  //|/.\|\\");
Console.WriteLine(@" ||  \ /  ||");
Console.WriteLine(@"============");
Console.WriteLine(@"|          |");
Console.WriteLine(@"|          |");
Console.WriteLine(@"|          |");